# Generated by Django 3.0.8 on 2020-08-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='token',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
