# Generated by Django 3.0.8 on 2020-09-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_seller_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile',
            field=models.BinaryField(null=True),
        ),
    ]
