# Generated by Django 3.0.8 on 2020-09-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_seller_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='status',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
