# Generated by Django 3.0.8 on 2020-09-02 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_seller_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='product_name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
