# Generated by Django 3.0.8 on 2020-08-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DieCastModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_code', models.CharField(max_length=254, null=True)),
                ('casting_name', models.CharField(max_length=254, null=True)),
                ('series', models.CharField(max_length=254, null=True)),
                ('year', models.CharField(max_length=254, null=True)),
                ('color', models.CharField(max_length=254, null=True)),
                ('loose_photo', models.BinaryField()),
            ],
        ),
    ]
