# Generated by Django 3.0.8 on 2020-08-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diecast', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diecastmodel',
            name='choice',
            field=models.CharField(choices=[('TL', 'Thailand'), ('ID', 'Indonesia'), ('ML', 'Malaysia'), ('CN', 'China')], default='TL', max_length=2),
        ),
    ]
