# Generated by Django 3.0.8 on 2020-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diecast', '0002_diecastmodel_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diecastmodel',
            name='choice',
            field=models.CharField(choices=[('Thaidland', 'Thailand'), ('Indonesia', 'Indonesia'), ('Malaysia', 'Malaysia'), ('China', 'China')], default='Thailand', max_length=20),
        ),
    ]
